"use strict"

module.exports = {
  "rules" : {
    "color-no-invalid-hex": true,
    "font-family-name-quotes": "always-where-recommended",
    "font-weight-notation": "numeric",
    "function-linear-gradient-no-nonstandard-direction": true,
    "function-name-case": "lower",
    "function-url-quotes": "always",
    "number-max-precision": 3,
    "time-min-milliseconds": 100,
    "unit-case": "lower",
    "unit-no-unknown": true,
    "value-keyword-case": "lower",
    "property-case": "lower",
    "property-no-unknown": true,
    "keyframe-declaration-no-important": true,
    "declaration-no-important": true,
    "declaration-block-no-duplicate-properties": [true, {
      "ignore": ["consecutive-duplicates"]
    }],
    "declaration-block-no-shorthand-property-overrides": true,
    "declaration-block-single-line-max-declarations": 2,
    "declaration-block-trailing-semicolon": "always",
    "block-no-empty": true,
    "selector-attribute-brackets-space-inside": "never",
    "selector-attribute-operator-space-after": "never",
    "selector-attribute-operator-space-before": "never",
    "selector-combinator-space-after": "always",
    "selector-combinator-space-before": "always",
    "selector-max-compound-selectors": 3,
    "selector-max-specificity": "0,5,5",
    "selector-pseudo-class-case": "lower",
    "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-element-case": "lower",
    "selector-pseudo-element-no-unknown": true,
    "selector-type-case": "lower",
    "selector-type-no-unknown": true,
    "selector-max-empty-lines": 0,
    "at-rule-name-case": "lower",
    "at-rule-name-space-after": "always",
    "indentation": 2,
    "max-nesting-depth": 5,
    "no-duplicate-selectors": true,
    "no-empty-source": true,
    "no-extra-semicolons": true,
    "no-invalid-double-slash-comments": true,
    "no-unknown-animations": true
  }
}
